# Generated by Django 3.2.8 on 2021-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_in', models.FileField(upload_to='', verbose_name='EXCEL список пациентов')),
            ],
            options={
                'verbose_name': 'ExcelInput',
                'verbose_name_plural': 'ExcelInputs',
            },
        ),
        migrations.CreateModel(
            name='GlikProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('date', models.DateField(verbose_name='№ИБ')),
                ('room', models.TextField(verbose_name='№ палаты')),
            ],
            options={
                'verbose_name': 'Глик профиль',
                'verbose_name_plural': 'Глик профиль',
            },
        ),
    ]
