# Generated by Django 3.2.9 on 2021-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('nIb', models.IntegerField(verbose_name='№ИБ')),
                ('room', models.TimeField(verbose_name='№ палаты')),
                ('date', models.DateField(verbose_name='Дата госпитализации')),
            ],
            options={
                'verbose_name': 'Список пациентов',
                'verbose_name_plural': 'Список пациентов',
            },
        ),
    ]
