# Generated by Django 3.2.9 on 2021-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='nIb',
            field=models.BigIntegerField(verbose_name='№ИБ'),
        ),
        migrations.AlterField(
            model_name='people',
            name='room',
            field=models.BigIntegerField(verbose_name='№ палаты'),
        ),
    ]
