# Generated by Django 3.2.9 on 2021-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20211117_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.TextField(verbose_name='Дата госпитализации'),
        ),
    ]
