# Generated by Django 3.2.9 on 2021-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_people_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='People1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('nIb', models.BigIntegerField(verbose_name='№ИБ')),
                ('room', models.BigIntegerField(verbose_name='№ палаты')),
                ('date', models.TextField(verbose_name='Дата госпитализации')),
            ],
            options={
                'verbose_name': 'Список пациентов',
                'verbose_name_plural': 'Список пациентов',
            },
        ),
    ]
