# Generated by Django 3.2.9 on 2021-11-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_people1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People1',
        ),
    ]
