# Generated by Django 3.2.9 on 2021-11-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_delete_people1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peaple1',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panel.people')),
            ],
            options={
                'verbose_name': 'Список пациентов1',
                'verbose_name_plural': 'Список пациентов1',
            },
            bases=('panel.people',),
        ),
    ]
