# Generated by Django 3.2.9 on 2021-11-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_peaple1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peaple1',
            new_name='People1',
        ),
    ]
