# Generated by Django 3.2.9 on 2021-11-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_rename_peaple1_people1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People1',
        ),
    ]
