# Generated by Django 3.2.9 on 2021-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_delete_people1'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='otdel',
            field=models.CharField(blank=True, choices=[('1-ое отделение', '1'), ('2-ое отделение', '2'), ('3-ое отделение', '3')], max_length=50, verbose_name='Отделение'),
        ),
    ]
