# Generated by Django 3.2.9 on 2021-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20211125_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdel',
            name='name',
            field=models.TextField(verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='otdel',
            name='short_name',
            field=models.TextField(verbose_name='Короткое название'),
        ),
    ]
