# Generated by Django 3.2.8 on 2021-12-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
