# Generated by Django 3.2.9 on 2021-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='nIb',
            field=models.TextField(verbose_name='№ИБ'),
        ),
    ]
